name: Workflow Test

on:
  push:
    branches: [ main ]
env:
  MY_VARIABLE: my-value
  
jobs:
  job-pass:
    runs-on: ubuntu-latest

    steps:
    - name: Echo success message
      run: echo $MY_VARIABLE
      run: echo "This job passed!"

  job-fail:
    runs-on: ubuntu-latest

    steps:
    - name: Echo failure message
      run: echo "This job failed!" && exit 1